[build]
  command = "npm run build"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/:splat"
  status = 200
  force = true
